name: Run Reddit API Script

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day

permissions:
    contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'  # Replace with your specific Python version if needed

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Make sure this file includes all necessary packages

    - name: Run Reddit API script
      run: python reddit_pull.py
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        PASSWORD: ${{ secrets.PASSWORD }}
        USERNAME: ${{ secrets.USERNAME }}

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add Data/  # This will stage all changes in the Data folder
        git commit -m "Update data from Reddit API" || exit 0
        git push